# Generated by Django 4.2.9 on 2024-02-07 07:08

from django.db import migrations, models
import django.utils.timezone
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=20, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=500, null=True)),
                ('pertanyaan', models.CharField(blank=True, max_length=500, null=True)),
                ('jawaban', models.CharField(blank=True, max_length=500, null=True)),
                ('is_view', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('waktu_pencatatan', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('tanggal_pembayaran', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10)),
                ('bulan', models.CharField(max_length=20)),
                ('kubikasi_awal', models.IntegerField()),
                ('kubikasi_akhir', models.IntegerField()),
                ('kubikasi_total', models.IntegerField()),
                ('tagihan_total', models.IntegerField()),
                ('tagihan_dibayar', models.IntegerField()),
                ('status_pembayaran', models.CharField(max_length=20)),
                ('sisa_pembayaran', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='website/static/image/')),
                ('status_bayar', models.CharField(blank=True, default='', max_length=20)),
                ('status_mesin', models.CharField(blank=True, default='', max_length=20)),
                ('status_kependudukan', models.CharField(blank=True, default='', max_length=20)),
                ('bulan_tagihan', models.CharField(blank=True, default='', max_length=20)),
                ('tahun_tagihan', models.CharField(blank=True, default='', max_length=20)),
                ('pemakaian_kubik_bulanan', models.IntegerField(blank=True, null=True)),
                ('biaya_pemakaian_bulanan', models.IntegerField(blank=True, null=True)),
                ('biaya_total_bulanan', models.IntegerField(blank=True, null=True)),
                ('encrypted_pemakaian_kubik_bulanan', models.CharField(blank=True, max_length=500, null=True)),
                ('encrypted_biaya_pemakaian_bulanan', models.CharField(blank=True, max_length=500, null=True)),
                ('encrypted_biaya_total_bulanan', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', website.models.CustomUserManager()),
            ],
        ),
    ]
