# Generated by Django 4.2.9 on 2024-02-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinformation',
            name='judul',
            field=models.CharField(max_length=20),
        ),
    ]
