# Generated by Django 4.2.7 on 2023-12-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biaya_pemakaian_bulanan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='biaya_total_bulanan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pemakaian_kubik_bulanan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
