# Generated by Django 4.2.9 on 2024-02-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinformation',
            name='judul',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
