# Generated by Django 4.2.9 on 2024-02-25 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_aboutinformation_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='tahun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='unique_id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aboutinformation',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='kubikasi_akhir',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='kubikasi_awal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='kubikasi_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='sisa_pembayaran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='tagihan_dibayar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='tagihan_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='waktu_pencatatan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
