# Generated by Django 4.2.7 on 2023-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_biaya_pemakaian_bulanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bulan_tagihan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tahun_tagihan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
