# Generated by Django 4.2.9 on 2024-02-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_paymenthistory_tahun_paymenthistory_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='tahun',
            field=models.IntegerField(),
        ),
    ]
