# Generated by Django 4.2.7 on 2023-12-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_bulan_tagihan_user_tahun_tagihan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='bulan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status_pembayaran',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='bulan_tagihan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_bayar',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_kependudukan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_mesin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahun_tagihan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
