# Generated by Django 4.2.7 on 2023-12-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_paymenthistory_bulan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/image/'),
        ),
    ]
