# Generated by Django 4.2.7 on 2023-12-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_user_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_biaya_total_bulanan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_pemakaian_bulanan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_pemakaian_kubik_bulanan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
