# Generated by Django 4.2.7 on 2023-12-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_encrypted_biaya_total_bulanan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='encrypted_pemakaian_bulanan',
            new_name='encrypted_biaya_pemakaian_bulanan',
        ),
    ]
